# Generated by Django 3.0.3 on 2020-05-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinkcounter', '0002_consumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='credit',
        ),
    ]
