# Generated by Django 3.0.3 on 2020-05-16 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinkcounter', '0005_resident_moved_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinkcounter.Resident')),
            ],
        ),
    ]
