# Generated by Django 3.0.3 on 2020-09-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkcounter', '0009_payment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
