# Generated by Django 3.0.3 on 2020-05-08 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drinkcounter', '0003_remove_resident_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumption',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
